import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { LUCIDE_ICONS, LucideIconProvider } from 'lucide-angular';
import {
  Shield,
  Users,
  AlertTriangle,
  Smartphone,
  Activity,
  ActivitySquare,
  Bell,
  CircleAlert,
  AlertCircle,
  Settings,
  CircleUser,
  LogOut,
  LogIn,
  MapPin,
  Radio,
  Clock,
  ClipboardList,
  SquarePen,
  Trash2,
  Zap,
  ChartColumn,
  Heart,
  Mail,
  Phone,
  ChevronDown,
  ChevronUp,
  UserCircle,
  BarChart3,
  LayoutDashboard,
  Battery,
  BatteryWarning,
  RefreshCw,
  MessageSquare,
  Calendar,
  User,
  Info,
  Braces,
  Terminal,
  Cpu,
  Wifi,
  Network,
  Thermometer,
  Siren,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  MoveVertical,
  CheckCircle,
  XCircle,
  X,
  Check,
  FileText,
  ChevronRight,
  ChevronLeft,
  Search,
  List,
  Lock,
  ArrowLeft,
  Gift,
  CalendarDays,
  Watch,
  Eye,
  EyeOff,
  HeartHandshake,
  IdCard,
  BatteryMedium,
} from 'lucide-angular';

import { routes } from './app.routes';
import { authInterceptor } from './interceptors/auth.interceptor';

const icons = {
  Shield,
  Users,
  AlertTriangle,
  Smartphone,
  Activity,
  ActivitySquare,
  Bell,
  CircleAlert,
  AlertCircle,
  Settings,
  CircleUser,
  LogOut,
  LogIn,
  MapPin,
  Radio,
  Clock,
  ClipboardList,
  SquarePen,
  Trash2,
  Zap,
  ChartColumn,
  Heart,
  Mail,
  Phone,
  ChevronDown,
  ChevronUp,
  UserCircle,
  BarChart3,
  LayoutDashboard,
  Battery,
  BatteryWarning,
  RefreshCw,
  MessageSquare,
  Calendar,
  User,
  Info,
  Braces,
  Terminal,
  Cpu,
  Wifi,
  Network,
  Thermometer,
  Siren,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  MoveVertical,
  CheckCircle,
  XCircle,
  X,
  Check,
  FileText,
  ChevronRight,
  ChevronLeft,
  Search,
  List,
  Lock,
  Eye,
  EyeOff,
  ArrowLeft,
  Gift,
  CalendarDays,
  Watch,
  HeartHandshake,
  IdCard,
  BatteryMedium,
};

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    { provide: LUCIDE_ICONS, multi: true, useValue: new LucideIconProvider(icons) },
  ],
};
